import { useReactiveVar } from '@apollo/client';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { isLoggedInVar } from '../apollo';

const Home: NextPage = () => {
  const isLoggedIn = useReactiveVar(isLoggedInVar);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>H1</h1>
      <Link href="/login">
        <a>Login</a>
      </Link>
      {isLoggedIn ? <div>Login</div> : <div>Logout</div>}
      <div>Home</div>
    </div>
  );
};

export default Home;
